server:
  port: 6006
  maxHttpHeaderSize: 10240000
  undertow:
    io-threads: 4
    worker-threads: 256
    buffer-size: 1024
    direct-buffers: true
    accesslog:
      dir: /usr/local/accesslogs/joyzone/
      enabled: true
      pattern: combined
      prefix: access_log.
      rotate: true
      suffix: log
    max-http-post-size: 10240000
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 300MB
  application:
    name: joyzone-business
  security:
    user:
      name: joyzone
      password: Joyzone
  swagger:
     enable: true
  redis:
     host: 127.0.0.1
     port: 6379
     timeout: 20000
     pool:
       max-active: 8
       min-adle: 0
       max-idle: 8
       max-wait: -1
mybatis:
  type-aliases-package:  com.joyzone.platform.core.model
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:/mapper/**.xml
mapper:
  mappers:
    - com.joyzone.platform.core.base.BaseMapper
  not-empty: true
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count:countSql
druid:
  url: jdbc:mysql://120.78.156.35:3306/joyzone?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
  driver-class: com.mysql.jdbc.Driver
  username: root
  password: Joyzone@hgz
  initialSize: 1
  min-idle: 1
  max-active: 20
  test-on-borrow: true
logging:
  config: classpath:logback.xml
using:
  spring:
    schedulerFactory: false
fileSize: 2048000
scale: 0.8
distance_range: 5000
tencent:
  oss:
    secretId: AKIDDJF0rh6KckRDjCnpyeeVBkYQNGMIDg9J
    secretKey:  1IRmyGn3FWlvukPSXKAQFy3vgF05rUwk
    bucket:  joyzone-1257127706
yunpian:  
  sms:
    apiKey: 129afa0712a781de56500b720e5f2c6e
easemob:
   host: http://a1.easemob.com/
   orgName: 1113190505010089
   appName: joyzone
   grantType: client_credentials
   clientId: YXA6eWR-kG9AEemCpmWWikCXLA
   clientSecret: YXA6XYMzIlVp-y-0BcbYbuxQC1nbDCg